[package]
name = "systemd-parser"
version = "0.2.0"
authors = ["Pancy <pancy@xerberus.net>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
pest = "2.0"
pest_derive = "2.0"

[lib]
name = "systemd_parser"
edition = "2018"



