[package]
name = "systemd-parser"
version = "0.1.0"
authors = ["Pancy <pancy@xerberus.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
pest = "2.1"
pest_derive = "2.1"

[lib]
name = "systemd_parser"
edition = "2018"



